name: shopping_list
description: "todo"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flex_color_scheme: ^7.3.1
  yaru: ^4.1.0
  cupertino_icons: ^1.0.8
  collection: ^1.18.0
  clock: ^1.1.1
  rxdart: ^0.27.7

  flutter_riverpod: ^2.5.1
  riverpod_annotation: any

  freezed_annotation: ^2.4.1
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  custom_lint:
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  build_runner: any
  build_verify: any
  freezed: ^2.5.2
  json_serializable:

dependency_overrides:
  intl: ^0.19.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/Lato/OFL.txt
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato/Lato-Black.ttf
          weight: 900
